//
//  WECeremonyHost.swift
//  WE
//
//  The Promise, on both phones, at the moment both people arrive.
//
//  WHY THIS IS NOT DRIVEN BY A STATE TRANSITION
//
//  The obvious hook already existed: `ContentView` watches for
//  `.waitingForPartner -> .ready` and shows an arrival screen. It is the wrong
//  mechanism, three times over. It fires only for the person who happens to be
//  looking at that screen at that instant, so the joiner never gets it. It
//  does not fire on the `.choosingHue` route at all. And an edge cannot
//  survive a relaunch, which is the one thing a ceremony spread over two
//  phones and possibly two days absolutely has to do.
//
//  So the ceremony is driven by persisted state instead: both devices ask the
//  same two questions and get the same two answers. Both behave identically
//  because neither is reacting to an event the other cannot see, a killed app
//  resumes on the held beat because `currentBeat` already means "the first
//  beat not yet kept", and there is no moment at which the trigger can be
//  missed.
//
//  WHAT DRIVES THE RE-READ
//
//  Presence, and only as a *tick*. `WECeremonyPresence` carries liveness and
//  nothing else — it never says who acknowledged what. When the other phone
//  attaches or reattaches, this asks the aggregate again. The aggregate is a
//  bare boolean per beat, and `ceremony_acknowledgements` is deliberately
//  absent from `FieldSupabaseBackend.observedTables`, because a realtime row
//  event would carry its own arrival time — the other person's timing wearing
//  a different hat.
//

import SwiftUI

@MainActor
struct WECeremonyHost: View {
    let backend: FieldSupabaseBackend
    let identity: FieldIdentity

    @State private var session: WECeremonySession?
    @State private var presence: WECeremonyPresence?

    var body: some View {
        Group {
            if let session, let ceremony = session.phase.ceremony {
                LivingConfluencePromise(
                    identity: identity,
                    // The viewer, so the field can strengthen this person's
                    // own hue when they give a beat. It is never used to draw
                    // the partner, and there is no state in which it could be:
                    // `held` is by definition this device having acted.
                    viewer: backend.viewerOwner,
                    ceremony: Binding(
                        get: { ceremony },
                        set: { _ in }
                    ),
                    keep: { beat in
                        Task { await session.keep(beat) }
                    },
                    onComplete: {}
                )
                .transition(.opacity)
            }
            // Every other phase draws nothing at all. `loading` in particular
            // must not draw: a default `WECeremonyState` has an empty `kept`,
            // so "no answer yet" and "on beat one" are the same value, and
            // guessing would flash the Promise over the zones on every cold
            // launch. See `WECeremonyPhase`.
        }
        .task {
            let session = session ?? WECeremonySession(backend: backend)
            self.session = session
            await session.load()
            await watchPresence(session)
        }
    }

    /// Joins the couple's ephemeral channel and re-reads the aggregate on
    /// every occupancy change.
    ///
    /// Nothing is written and no table is touched, so no partner-visible
    /// event is generated by being here. The stream's first value arrives on
    /// join, which is what makes the second person's arrival the thing that
    /// moves the ceremony rather than a timer.
    private func watchPresence(_ session: WECeremonySession) async {
        guard session.phase.presentsPromise else { return }

        let channel = presence ?? WECeremonyPresence(
            client: backend.client,
            coupleID: backend.coupleID
        )
        presence = channel

        for await _ in channel.presence() {
            guard session.phase.presentsPromise else { return }
            await session.refresh()
        }
    }
}
